version: '3'

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - 2181:2181

  kafka:
    image: docker.io/bitnami/kafka:2-debian-10
    container_name: kafka
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 9093:9093

  api:
    build:
      context: .
    container_name: getting-started-kafka-node
    entrypoint: dockerize -wait tcp://kafka:9092 -timeout 40s ./.docker/entrypoint.sh
    depends_on:
      - zookeeper
      - kafka
    volumes:
      - .:/home/node/app
    ports:
      - 3333:3333
